import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import noticiasData from '../database/tecnologia.json';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pesquisa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}
        <footer>
       {/* <div>
          
          {noticiasData.noticiastecnologia.map(noticia => (
            <div key={noticia.Id}>
              <h2>{noticia.titulo}</h2>
          
              <img src={noticia.LinkImagen} alt="Imagem da Notícia" />
            </div>
          ))}
        </div>*/}
          <Footer />
          </footer>
      </body>
    </html>
  );
}
